language: python
dist: bionic

env:
  global:
    - PIPENV_VERBOSITY=-1

matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "nightly"
  allow_failures:
    - python: "nightly"

before_install:
  - pip3 install --upgrade setuptools

install:
  - python setup.py install
  - pipenv install --dev

# tests and checks
before_script:
  - pipenv run check:lint
  - pipenv run check:style

# program exec
script:
  - tpsp --help
  - tpsp --version
  - tpsp --copyright

# now that we know the program is installed and reachable, issue the commands
after_success:
  - tpsp cptm
  - sleep 5  # pause between calls to avoid too many requests
  - tpsp metro
  - sleep 5
  - tpsp cptm --json
  - sleep 5
  - tpsp metro --json
  - sleep 5
