language: python
dist: bionic

env:
  global:
    - PIPENV_VERBOSITY=-1

matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "nightly"
  allow_failures:
    - python: "nightly"


install:
  - pipenv install --dev

script:
  - pipenv run check:lint
  - pipenv run check:style
